Version bump for rebuild
Update custom minio scripts

Note: minio-client mirror or cp doesn't include symlinks.

diff --git a/hugo-nginx/hugo-nginx.d/local/share/cook/templates/mirrorsync.sh.in b/hugo-nginx/hugo-nginx.d/local/share/cook/templates/mirrorsync.sh.in
--- a/hugo-nginx/hugo-nginx.d/local/share/cook/templates/mirrorsync.sh.in
+++ b/hugo-nginx/hugo-nginx.d/local/share/cook/templates/mirrorsync.sh.in
@@ -6,17 +6,26 @@ set -o pipefail
 
 export PATH=/usr/local/bin:$PATH
 
-mywebpath="/usr/local/www/%%sitename%%"
-mys3path="myminio/%%bucketname%%"
+mywebpath="/usr/local/www/%%sitename%%/"
+mys3path="myminio/%%bucketname%%/"
 limit="50M"
 
 _check_minio() {
-	/usr/local/bin/minio-client --insecure stat "$mys3path"
+	/usr/local/bin/minio-client \
+	 --insecure stat "$mys3path"
 }
 
 _mirror_to_minio() {
-	/usr/local/bin/minio-client --insecure mirror --limit-upload "$limit" \
-     --retry --limit-download "$limit" --overwrite "$mywebpath" "$mys3path"
+	/usr/local/bin/minio-client \
+	 --insecure \
+	 mirror \
+	 --overwrite \
+	 --limit-upload "$limit" \
+	 --limit-download "$limit" \
+	 --quiet \
+	 --json \
+	 --no-color \
+	 "$mywebpath" "$mys3path"
 }
 
 # change directory to the webpath
@@ -24,9 +33,8 @@ cd "$mywebpath" || exit 1
 
 # If minio check is valid, then mirror
 if _check_minio; then
-	_mirror_to_minio
-	printf "\nS3 mirror success\n\n"
+        _mirror_to_minio
 else
-	printf "\nAn error occurred. Could not access bucket. Exiting. Contact Admin.\n\n"
-	exit 1
+        printf "\nAn error occurred. Could not access bucket. Exiting. Contact Admin.\n\n"
+        exit 1
 fi
